---
- name: Deploy Docker services
  hosts: artifactory
  gather_facts: false

  tasks:
    - name: Install pip
      raw: curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py && python get-pip.py --user
      become: true

    - name: Install docker-py
      command: pip install docker-py
      become: true

    - name: Create Docker network
      docker_network:
        name: artifactorynet

    - name: Create volume for artifactory_data
      docker_volume:
        name: artifactory_data

    - name: Create volume for postgresql_data
      docker_volume:
        name: postgresql_data

    - name: Start db container
      docker_container:
        name: db
        image: postgres
        state: started
        restart_policy: always
        networks:
          - name: artifactorynet
        ports:
          - "172.31.76.255:5432:5432"
        environment:
          POSTGRES_DB: jfrogdb
          POSTGRES_USER: artifactory
          POSTGRES_PASSWORD: artifactorypassword
        volumes:
          - /data/postgresql:/var/lib/postgresql/data
        ulimits:
          nproc: 65535
          nofile:
            soft: 32000
            hard: 40000
        deploy:
          resources:
            limits:
              cpus: '2'
              memory: 512M
            reservations:
              cpus: '0.0001'
              memory: 20M

    - name: Start artifactory container
      docker_container:
        name: artifactory
        image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.55.13
        state: started
        restart_policy: always
        networks:
          - name: artifactorynet
        ports:
          - "172.31.76.255:8081:8081"
          - "172.31.76.255:8082:8082"
        environment:
          JF_SHARED_DATABASE_TYPE: postgresql
          JF_SHARED_DATABASE_USERNAME: artifactory
          JF_SHARED_DATABASE_PASSWORD: artifactorypassword
          JF_SHARED_DATABASE_URL: jdbc:postgresql://db:5432/jfrogdb
          JF_SHARED_DATABASE_DRIVER: org.postgresql.Driver
        volumes:
          - artifactory_data:/var/opt/jfrog/artifactory
        ulimits:
          nproc: 65535
          nofile:
            soft: 32000
            hard: 40000
        deploy:
          resources:
            limits:
              cpus: '2'
              memory: 2148M