version: "3"

services:
  db:
    image: postgres:14-alpine
    #image: postgres:15-alpine
    container_name: db
    ports:
      - "172.31.86.110:5432:5432"
    networks:
      - sonarnet
    environment:
      #- POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: always

  sonarqube:
    #image: sonarqube:10.0.0-developer
    image: sonarqube:lts-developer
    #image: sonarqube:9.9.1-developer
    container_name: sonarqube
    expose:
      - 9000
    ports:
      - "172.31.86.110:9000:9000"
    networks:
      - sonarnet
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://172.31.86.110:5432/db?currentSchema=public
      #- SONAR_JDBC_URL=jdbc:postgresql://172.31.86.110:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      #- sonarqube_conf:/opt/sonarqube/conf
      #- /home/ubuntu/sonar.properties:/opt/sonarqube/conf/sonar.properties
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    restart: always

networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data: