---
- name: Run the playbook
  hosts: artifactory
  gather_facts: false
  vars:
    services:
      db:
        image: postgres
        container_name: db
        ports:
          - "172.31.76.255:5432:5432"
        networks:
          - artifactorynet
        environment:
          - POSTGRES_DB=jfrogdb
          - POSTGRES_USER=artifactory
          - POSTGRES_PASSWORD=artifactorypassword
        volumes:
          - /data/postgresql:/var/lib/postgresql/data
        restart: always
        ulimits:
          nproc: 65535
          nofile:
            soft: 32000
            hard: 40000
        deploy:
          resources:
            limits:
              cpus: '2'
              memory: 512M
            reservations:
              cpus: '0.0001'
              memory: 20M
      artifactory:
        image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.55.13
        expose:
          - 8081
          - 8082
        container_name: artifactory
        ports:
          - "172.31.76.255:8081:8081"
          - "172.31.76.255:8082:8082"
        networks:
          - artifactorynet
        depends_on:
          - db
        links:
          - db
        volumes:
          - artifactory_data:/var/opt/jfrog/artifactory
          - ./master.key:/var/opt/jfrog/artifactory/var/etc/security/master.key
        environment:
          - DB_TYPE=postgresql
          - DB_USER=artifactory
          - DB_PASSWORD=password
          - JF_SHARED_DATABASE_TYPE=postgresql
          - JF_SHARED_DATABASE_USERNAME=artifactory
          - JF_SHARED_DATABASE_PASSWORD=artifactorypassword
          - JF_SHARED_DATABASE_URL=jdbc:postgresql://db:5432/jfrogdb
          - JF_SHARED_DATABASE_DRIVER=org.postgresql.Driver
          - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
        restart: always
        ulimits:
          nproc: 65535
          nofile:
            soft: 32000
            hard: 40000
        deploy:
          resources:
            limits:
              cpus: '2'
              memory: 2148M
            reservations:
              cpus: '0.0001'
              memory: 20M
  tasks:
  - name: Deploy Artifactory
    community.docker.docker_compose:
      project_name: artifactory
      project_src: .
      state: present